x=input('Input Your First Number : ')
y=input('Input Your Second Number : ')
z=input('Input Your Third Number : ')
v=input('Input Your Fourth Number : ')
k=input('Input Your Fifth Number : ')
print("Float of %s"%x, " Equal %s"%float(x)) 
print("complex of %s"%x, " Equal %s"%complex(x))
print("Float of %s"%y, " Equal %s"%float(y)) 
print("complex of %s"%y, " Equal %s"%complex(y))
print("Float of %s"%z, " Equal %s"%float(z)) 
print("complex of %s"%z, " Equal %s"%complex(z))
print("Float of %s"%v, " Equal %s"%float(v)) 
print("complex of %s"%v, " Equal %s"%complex(v))
print("Float of %s"%k, " Equal %s"%float(k)) 
print("complex of %s"%k, " Equal %s"%complex(k))

