print('\nโปรแกรมหยิบสินค้าใส่ตะกร้า')
shoplist=[]
shoplist.append(input('หยิบสินค้าชิ้นที่ 1 : '))
shoplist.append(input('หยิบสินค้าชิ้นที่ 2 : '))
shoplist.append(input('หยิบสินค้าชิ้นที่ 3 : '))
shoplist.append(input('หยิบสินค้าชิ้นที่ 4 : '))
shoplist.append(input('หยิบสินค้าชิ้นที่ 5 : '))
print('หยิบสินค้าใส่ตะกร้ามีดังนี้')
print('1.:',shoplist[0])
print('2.:',shoplist[1])
print('3.:',shoplist[2])
print('4.:',shoplist[3])
print('5.:',shoplist[4])
